base_sql = """
WITH
  COUNTS AS (
  SELECT
    DATE(DATE_CREATED) AS DATE,
    CAST(FORMAT("%02d",(EXTRACT(MONTH
          FROM
            DATE(DATE_CREATED)))) AS STRING) AS MONTH,
    CAST(EXTRACT(YEAR
      FROM
        DATE(DATE_CREATED)) AS STRING) AS YEAR,
    ICCE,
    COUNT(REPLACEMENT) AS REPLACEMENT_CNTS
  FROM
    `musc-lineara.musc.custom_recruitment`
  GROUP BY
    DATE,
    MONTH,
    YEAR,
    ICCE
  ORDER BY
    DATE)
SELECT
  ICCE,
  CONCAT(YEAR, MONTH) AS POST_PD,
  TRUE AS TARGET
FROM
  COUNTS WHERE ICCE IS NOT NULL
GROUP BY
  ICCE,
  POST_PD
ORDER BY POST_PD
"""

prov_sql = """
WITH
  PROV_PROD AS (
  SELECT
    * EXCEPT(ICCE_NAME,
      PROVIDER_NPI,
      PROVIDER_NUMBER,
      NEW_PATIENT_APPTS_14_DAYS,
      NEW_PATIENT_APPTS_SCHEDULED,
      NEW_PATIENT_APPTS_TOTAL_LAG,
      COMPLETED_APPTS,
      POSSIBLE_SCHEDULED_APPTS,
      SLOTS_AVAILABLE),
    PROVIDER_NPI AS NPI,
    ICCE_NAME AS ICCE,
    COALESCE(SAFE_CAST(NEW_PATIENT_APPTS_14_DAYS AS FLOAT64),
      0.0) AS NEW_PATIENT_APPTS_14_DAYS,
    COALESCE(SAFE_CAST(NEW_PATIENT_APPTS_SCHEDULED AS FLOAT64),
      0.0) AS NEW_PATIENT_APPTS_SCHEDULED,
    COALESCE(SAFE_CAST(NEW_PATIENT_APPTS_TOTAL_LAG AS FLOAT64),
      0.0) AS NEW_PATIENT_APPTS_TOTAL_LAG,
    COALESCE(SAFE_CAST(COMPLETED_APPTS AS FLOAT64),
      0.0) AS COMPLETED_APPTS,
    COALESCE(SAFE_CAST(POSSIBLE_SCHEDULED_APPTS AS FLOAT64),
      0.0) AS POSSIBLE_SCHEDULED_APPTS,
    COALESCE(SAFE_CAST(SLOTS_AVAILABLE AS FLOAT64),
      0.0) AS SLOTS_AVAILABLE,
    SAFE_DIVIDE(COALESCE(SAFE_CAST(COMPLETED_APPTS AS FLOAT64),
      0.0),
    (COALESCE(SAFE_CAST(POSSIBLE_SCHEDULED_APPTS AS FLOAT64),
      0.0))) AS PERCENTAGE_COMPLETED_APPTS_AVAILABLE,
    SAFE_DIVIDE(COALESCE(SAFE_CAST(COMPLETED_APPTS AS FLOAT64),
      0.0),
    (COALESCE(SAFE_CAST(SLOTS_AVAILABLE AS FLOAT64),
      0.0))) AS PERCENTAGE_COMPLETED_SLOTS_AVAILABLE
  FROM
    `musc-lineara.musc.PROVIDER_PRODUCTIVITY_2`)
SELECT
  *
FROM
  PROV_PROD
"""
